'use client';

import { useState } from 'react';
import { Badge, Button, Card } from '@/components/ui/Primitives';
import { Icon } from '@/components/ui/Icon';
import { answerPoints, difficultyLabel, questionText } from '@/lib/format';

function QuestionEditor({ question, onCancel, onSave, saving }) {
  const [draft, setDraft] = useState({ question: questionText(question), answer: answerPoints(question).join('\n'), why: question.why || '' });
  const update = (field) => (event) => setDraft((current) => ({ ...current, [field]: event.target.value }));
  return <div className="space-y-4"><div><label className="field-label" htmlFor={`question-${question.id}`}>Question prompt</label><textarea className="field-input min-h-24" id={`question-${question.id}`} onChange={update('question')} value={draft.question} /></div><div><label className="field-label" htmlFor={`answer-${question.id}`}>Answer outline <span className="font-normal text-muted">(one point per line)</span></label><textarea className="field-input min-h-28" id={`answer-${question.id}`} onChange={update('answer')} value={draft.answer} /></div><div><label className="field-label" htmlFor={`why-${question.id}`}>Why it matters</label><input className="field-input" id={`why-${question.id}`} onChange={update('why')} value={draft.why} /></div><div className="flex justify-end gap-2"><Button onClick={onCancel} type="button" variant="quiet">Cancel</Button><Button disabled={saving || !draft.question.trim() || !draft.answer.trim()} onClick={() => onSave({ question: draft.question, expectedAnswerPoints: draft.answer.split('\n').map((item) => item.trim()).filter(Boolean), why: draft.why })} type="button">{saving ? 'Saving…' : 'Save changes'}</Button></div></div>;
}

function QuestionCard({ question, index, total, editing, saving, onEdit, onCancel, onSave, onPin, onMove, onDelete }) {
  const points = answerPoints(question);
  return <Card className={`p-5 sm:p-6 ${question.pinned ? 'border-brand-200' : ''}`}><div className="flex gap-4"><div className="hidden w-7 shrink-0 pt-1 text-center sm:block"><span className="text-xs font-semibold text-muted">{String(index + 1).padStart(2, '0')}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge>{question.category || 'role_specific'}</Badge><Badge tone="gray">{difficultyLabel(question.difficulty)}</Badge><Badge tone={question.status === 'edited' ? 'amber' : 'gray'}>{question.status === 'edited' ? 'Edited' : 'Generated'}</Badge>{question.pinned && <Badge tone="green">Pinned</Badge>}</div>{editing ? <div className="mt-5"><QuestionEditor onCancel={onCancel} onSave={onSave} question={question} saving={saving} /></div> : <><h3 className="mt-4 text-base font-semibold leading-7 text-ink">{questionText(question)}</h3><div className="mt-5 grid gap-5 md:grid-cols-[1fr_180px]"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">Answer outline</p><ul className="mt-2 space-y-2">{points.map((point, pointIndex) => <li className="flex gap-2 text-sm leading-5 text-muted" key={`${question.id}-${pointIndex}`}><Icon className="mt-1 shrink-0 text-brand-600" name="check" size={14} />{point}</li>)}</ul></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">Covers</p><div className="mt-2 flex flex-wrap gap-1.5">{(question.requirementRefs || []).map((ref) => <Badge key={ref} tone="gray">{ref}</Badge>)}</div>{question.why && <p className="mt-3 text-xs leading-5 text-muted">{question.why}</p>}</div></div></>}</div><div className="flex shrink-0 flex-col items-end gap-2"><div className="flex gap-1"><Button aria-label={`Move ${question.id} up`} disabled={index === 0 || saving} onClick={() => onMove(-1)} title="Move up" variant="quiet"><Icon className="rotate-[-90deg]" name="arrow" size={15} /></Button><Button aria-label={`Move ${question.id} down`} disabled={index === total - 1 || saving} onClick={() => onMove(1)} title="Move down" variant="quiet"><Icon className="rotate-90" name="arrow" size={15} /></Button></div><div className="flex gap-1"><Button aria-label={`Edit ${question.id}`} onClick={onEdit} title="Edit question" variant="quiet"><Icon name="edit" size={15} /></Button><Button aria-label={`Pin ${question.id}`} onClick={onPin} title={question.pinned ? 'Unpin question' : 'Pin question'} variant="quiet"><Icon className={question.pinned ? 'text-brand-600' : ''} name="pin" size={15} /></Button><Button aria-label={`Delete ${question.id}`} disabled={saving || total <= 1} onClick={onDelete} title={total <= 1 ? 'At least one question is required' : 'Delete question'} variant="quiet"><Icon name="trash" size={15} /></Button></div></div></div></Card>;
}

export default function QuestionsPanel({ kit, onEdit, onPin, onReorder, onSave, onDelete, savingId, editingId, onCancelEdit }) {
  const questions = kit?.questions || [];
  return <div className="space-y-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">Question bank</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-ink">Make the questions yours.</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-muted">Edit locally, then save deliberately. Pin the questions you want to revisit before an interview.</p></div><Badge tone="green">{questions.length} questions</Badge></div>{questions.length === 0 ? <Card className="p-8 text-center text-sm text-muted">No questions were generated for this kit.</Card> : questions.map((question, index) => <QuestionCard editing={editingId === question.id} index={index} key={question.id} onCancel={onCancelEdit} onDelete={() => onDelete(question)} onEdit={() => onEdit(question.id)} onMove={(direction) => onReorder(index, direction)} onPin={() => onPin(question)} onSave={(changes) => onSave(question.id, changes)} question={question} saving={savingId === question.id} total={questions.length} />)}</div>;
}
