import { Badge, Button, Card } from '@/components/ui/Primitives';
import { Icon } from '@/components/ui/Icon';

const labels = ['', 'New', 'Shaky', 'Getting there', 'Comfortable', 'Confident'];

export default function PracticeCard({ item, index, total, revealed, saving, onReveal, onMove, onUpdate }) {
  const practice = item.practice || {};
  return <Card className="overflow-hidden"><div className="border-b border-line bg-[#fbfcfa] px-5 py-4 sm:px-7"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Practice Mode</p><h2 className="mt-1 text-lg font-semibold text-ink">Card {index + 1} of {total}</h2></div><Badge tone={practice.covered ? 'green' : 'amber'}>{practice.covered ? 'Covered' : 'Keep practicing'}</Badge></div><p className="mt-2 text-xs text-muted">{practice.confidence ? `${practice.confidence}/5 · ${labels[practice.confidence]}` : 'Not rated yet'}</p></div><div className="p-5 sm:p-8"><div className="mx-auto max-w-2xl rounded-2xl border border-line bg-white px-5 py-8 text-center sm:px-10 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-brand-600">Question</p><h3 className="mt-4 text-xl font-semibold leading-8 text-ink">{item.flashcard?.front || item.flashcard?.term || 'Untitled card'}</h3>{revealed ? <div className="mt-7 border-t border-line pt-6 text-left"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">Answer outline</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-ink">{item.flashcard?.back || item.flashcard?.definition || 'No answer outline was recorded.'}</p></div> : <Button className="mt-7" onClick={onReveal} variant="secondary">Reveal answer</Button>}</div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto_1fr]"><Button disabled={index === 0 || saving} onClick={() => onMove(-1)} variant="quiet"><Icon className="rotate-180" name="arrow" size={16} />Previous</Button><div className="flex items-center justify-center gap-2"><Button disabled={saving || !practice.covered} onClick={() => onUpdate({ covered: false })} variant="quiet">Uncovered</Button><Button disabled={saving || practice.covered} onClick={() => onUpdate({ covered: true })} variant="quiet"><Icon name="check" size={15} />Covered</Button></div><Button disabled={index === total - 1 || saving} onClick={() => onMove(1)} variant="quiet">Next<Icon name="arrow" size={16} /></Button></div><div className="mt-5 border-t border-line pt-5"><p className="text-sm font-semibold text-ink">How confident are you?</p><p className="mt-1 text-xs text-muted">Your answer updates the backend practice state.</p><div className="mt-4 grid grid-cols-5 gap-2">{[1, 2, 3, 4, 5].map((value) => <button aria-label={`Set confidence ${value}`} className={`rounded-lg border px-2 py-3 text-sm font-semibold transition ${practice.confidence === value ? 'border-brand-500 bg-brand-50 text-brand-700' : 'border-line bg-white text-muted hover:border-brand-300 hover:text-brand-700'}`} disabled={saving} key={value} onClick={() => onUpdate({ confidence: value })} type="button">{value}</button>)}</div></div></div></Card>;
}
